// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

export class Id {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Id {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

bits():bigint {
  return this.bb!.readUint64(this.bb_pos);
}

depth():number {
  return this.bb!.readUint8(this.bb_pos + 8);
}

static sizeOf():number {
  return 16;
}

static createId(builder:flatbuffers.Builder, bits: bigint, depth: number):flatbuffers.Offset {
  builder.prep(8, 16);
  builder.pad(7);
  builder.writeInt8(depth);
  builder.writeInt64(bits);
  return builder.offset();
}

}
