// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

export class Id {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Id {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

bits():number {
  return this.bb!.readUint32(this.bb_pos);
}

depth():number {
  return this.bb!.readUint8(this.bb_pos + 4);
}

static sizeOf():number {
  return 8;
}

static createId(builder:flatbuffers.Builder, bits: number, depth: number):flatbuffers.Offset {
  builder.prep(4, 8);
  builder.pad(3);
  builder.writeInt8(depth);
  builder.writeInt32(bits);
  return builder.offset();
}

}
